kind: pipeline
name: vs-build-on-amd64

platform:
  os: windows
  arch: amd64

steps:
- name: build
  image: compulim/msbuild
  commands:
  - msbuild drone_ci_test.sln /p:Configuration=Debug
  volumes:
  - name: docker
    path: C:\code

